ALTER TABLE reviews DISABLE ROW LEVEL SECURITY;
ALTER TABLE projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE certificates DISABLE ROW LEVEL SECURITY;
ALTER TABLE timeline DISABLE ROW LEVEL SECURITY;
ALTER TABLE contacts DISABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE reviews TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE projects TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE certificates TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE timeline TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE contacts TO anon, authenticated;
DO $$ DECLARE r RECORD; BEGIN
IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname='supabase_realtime') THEN
FOR r IN SELECT 'certificates' t UNION ALL SELECT 'projects' UNION ALL SELECT 'timeline' UNION ALL SELECT 'reviews' UNION ALL SELECT 'contacts' LOOP
BEGIN EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE %I', r.t); EXCEPTION WHEN duplicate_object THEN NULL; END;
END LOOP; END IF; END $$;
